/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElPopover: typeof import('element-plus/es')['ElPopover']
    IconButton: typeof import('./src/components/IconButton/index.vue')['default']
    ToolbarLayout: typeof import('./src/components/VcpToolbar/ToolbarLayout.vue')['default']
    VcpToolbar: typeof import('./src/components/VcpToolbar/index.vue')['default']
    VcpTracksPanel: typeof import('./src/components/VcpTracksPanel/index.vue')['default']
    VideoClipPanel: typeof import('./src/components/VideoClipPanel.vue')['default']
  }
}
